"""Generate/verify the CURRENT RELEASE (v1.1.0) README block, read from
results/final_v4_1/ -- separate from tools/update_readme_results.py, which
remains scoped to results/final_v2/ and is not modified here.

    python tools/update_readme_current_release.py           # write
    python tools/update_readme_current_release.py --check    # verify only
"""

from __future__ import annotations

import argparse
import json
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
README_PATH = os.path.join(REPO_ROOT, "README.md")
CAMPAIGN_PATH = os.path.join(REPO_ROOT, "results", "final_v4_1", "campaign_results.json")

BEGIN = "<!-- BEGIN CURRENT RELEASE RESULTS (v1.1.0 / final_v4_1) -->"
END = "<!-- END CURRENT RELEASE RESULTS -->"


def render(data):
    s = data["case_b_v1_1_structure"]
    q = data["audit_queries"]
    inj = data["case_b_v1_1_injections"]
    det = data["determinism"]
    mc = data["monte_carlo"]
    ld = data["ldrea_ulb"]
    fv = data["freeze_verification_prospective_v4"]
    ieee = data["ieee_check_v4"]
    ts = data["test_suite"]

    lines = [BEGIN, "## Current release: v1.1.0", "",
             f'**Reportable campaign:** `results/final_v4_1/`<br>',
             f'**Scientific freeze:** `{data["freeze_tag"]}`<br>',
             f'**Freeze commit:** `{data["freeze_commit"]}`<br>',
             "**Manifest:** 461 files, 32 roles, root "
             "`0640ad1e7a703879d4b9083a088f5b562b638173590292a2c1aed1625102e0e6`",
             "",
             "| | Case A | Case B v1.1 |", "|---|---|---|",
             f'| Bundle SHA-256 | `{data["case_a_hash"]["actual"]}` | `{data["case_b_v1_1_hash"]["actual"]}` |',
             f'| Q1-Q10 | {q["case_a"]["passed"]}/{q["case_a"]["total"]} | {q["case_b_v1_1"]["passed"]}/{q["case_b_v1_1"]["total"]} |',
             f'| Determinism (paired, 62 runs total) | {det["per_case"]["case_a"]["TD"]["value"]:.3f} | {det["per_case"]["case_b_v1_1"]["TD"]["value"]:.3f} |',
             f'| Monte Carlo max FP_heat | {mc["case_a_max_FP_heat"]["value"]} (risk {mc["case_a_max_FP_heat"]["risk_id"]}) | {mc["case_b_v1_1_max_FP_heat"]["value"]} (risk {mc["case_b_v1_1_max_FP_heat"]["risk_id"]}) |',
             "",
             f'Case B v1.1 structure: {s["risk_count"]} risks, {s["acs_count"]} Approved Control '
             f'Specifications, {s["risk_derived_predicate_count"]} risk-derived predicates, '
             f'{s["compiler_invariant_predicate_count"]} compiler invariants, '
             f'{s["predicate_count"]} predicates total.',
             "",
             f'**Negative fixtures:** {data["negative_fixtures"]["detected"]}/{data["negative_fixtures"]["total"]} detected '
             f'(covering the ten canonical queries above; not ten additional queries).',
             "",
             f'**Case B v1.1 injections (13 scenarios):** authorization_decision '
             f'{inj["authorization_decision_counts"]}; release_decision '
             f'{inj["release_decision_counts"]} -- release_decision is not a fourth peer '
             f'authorization outcome.',
             "",
             f'**Tests:** {ts["tests"]} passed, {ts["failures"]} failed, {ts["skipped"]} skipped.',
             "",
             f'**ieee-check-v4:** {ieee["status"]} ({ieee["stage_count"]} stages). '
             f'**Freeze verification:** {"PASS" if fv["passed"] else "FAIL"} '
             f'({fv["checks"]} checks, {fv["failures"]} failures).',
             "",
             f'**L-DREA/ULB:** original {ld["rows"]:,}-row experiment '
             f'({ld["pinned_repository"]} @ `{ld["pinned_commit"][:12]}`) reproduced fresh, unmodified: '
             f'{ld["fraud_labelled_rows"]} fraud-labelled, {ld["false_permit_count"]} false permits, '
             f'{ld["false_denial_count"]} false denials. GC-IR predicate-family correspondence: '
             f'{ld["correspondence_summary"]["exact"]} exact, {ld["correspondence_summary"]["family"]} family, '
             f'{ld["correspondence_summary"]["not_established"]} not_established. No new v1.1 corpus replay '
             f'was executed; no fraud-detection claim is made.',
             "",
             "```bash",
             "python tools/show_results_v1_1_0.py          # current release (this section)",
             "python tools/show_results_v1_1_0.py --json",
             "python tools/show_results.py                 # historical v1.0.5 / final_v2 campaign",
             "```",
             "",
             "This section is generated by `python tools/update_readme_current_release.py`; "
             "check it without modifying README with `python tools/update_readme_current_release.py --check`.",
             END]
    return "\n".join(lines)


def replace_or_insert(text, block):
    if BEGIN in text and END in text:
        start, end = text.index(BEGIN), text.index(END)
        return text[:start] + block + text[end + len(END):]
    # Insert immediately before the historical auto-generated block if present,
    # else before the first "---" divider, else at the end.
    marker = "<!-- BEGIN AUTO-GENERATED MEASURED RESULTS -->"
    if marker in text:
        idx = text.index(marker)
        return text[:idx] + block + "\n\n" + text[idx:]
    return text.rstrip("\n") + "\n\n" + block + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    with open(CAMPAIGN_PATH, encoding="utf-8") as fh:
        data = json.load(fh)
    block = render(data)

    with open(README_PATH, encoding="utf-8") as fh:
        current = fh.read()

    updated = replace_or_insert(current, block)

    if args.check:
        if updated != current:
            print("README current-release block is stale; run "
                  "`python tools/update_readme_current_release.py`")
            return 1
        print("README current-release block matches final_v4_1 evidence.")
        return 0

    with open(README_PATH, "w", encoding="utf-8") as fh:
        fh.write(updated)
    print("Updated the CURRENT RELEASE README block.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
